language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: uJFbnbXCwvf5caNoaJ50fJC27B6UwlauHR0z5F+BY7poq4CD0/TxoV83iDADOdHOMIh5vKXAPxOhEINZGmVFwgkeO3l0favpznLVPTfgGqdPfRzIEo65+imanAPioaibgXkKxUwYtAks67FHsirU5KRU02NNhoTFFdL0BKUV3F0ar8TazUfHmMwvvqYPN4MeLvcqYXzfsBlfXMV5fEOOuGR6WKzlYeq4zLqw5V8gT+8svfpynvPlDmOY5DE6HL9M9VocP5Nq6Yn9TjkNVYV9kGbFFs9eAdgs1CCcmr0mjPhPK8JdkUroQB0m8thl5kb+wDyB76ZbC8QeRXMDKku/HYVao3Mm9dG3Y8LDN5y+GyViu6n4X1ssMPDplYPRmnEIfcSw23nxmN/c7qQT49COth6SxRAYGIO1jWJngmM0ezSlsNGvWFya977Kzrio0nMXVXSuODK/eFKwSgXXrfURJJgvIopTPdmqUTppnqMAKfybUWksHS0BdBulZ17Z0b6GkwGR5GAGsJht2vxEPHF0CYJV63W3S9PomrnvrunKL2igTXoawsDlPuRBF1iHDDl4jQAqTt+rD9kE5roo4Hv1Pl2lEk8B/tTGsrXelE2cFIx9IdXNS+bvikKHKjoJYLMj/aRSTIC2bCezXJ3a5hZ+Cng5dKjuAN3YBFIdEJgo87Q=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
